DELAY_SEC = 10
SAVE_DIR = './images/'
LOGS_DIR = './logs/'
VIDEO_SRC = 'url'
OUTPUT_IMG_SHAPE = (1920, 1080)
SENDER_EMAIL = 'your_email@mail.ru'
RECEIVER_EMAIL = 'receiver@example.com'
SMTP_PASSWORD = 'SMTP_password'
SERVER_PORT = 8000
